target 'sure' do
  pod 'AppAuth', '>= 0.94'
  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'react-native-maps', :path => '../node_modules/react-native-maps'

  pod 'RNSketchCanvas', :path => '../node_modules/@terrylinla/react-native-sketch-canvas'

  pod 'react-native-camera', :path => '../node_modules/react-native-camera'

  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  pod 'react-native-video', :path => '../node_modules/react-native-video'

end

